language: node_js
node_js: node

cache:
  directories:
    - node_modules

install: 
    - echo "install"
    - export TZ='Asia/Shanghai'

before_script:
  - echo "before_script"
  - git checkout hexo

env:
  global:
    - GH-REF: github.com/cd-butterfly/cd-butterfly.github.io.git
    - secure: "lGQsn0P/vOl6A/JFzOxseQ6u8Z/QnxODzH76pxX4auP/vIEa0gixhcDj4vXpJx4FeQpTrDnQBrzvOCNltlXvvRTBKC+oZe8jPkZbu0enNT/cKVO9ltn3I5jz3Upqrb3YmUK3nTW8Jdck8Qwc87xfKoHU2aBOAfZrDJIjWZjXe8B93ntW1M83XDGyssbDHj0ANFE6EPYSAgsuDPJ77e9j4ttxlKsBTaeAiITlVz8BTg+cMNgG9JzPLFe8vI+8a4KlThQzHIwZh3SheWkdctTFUWsJkjRwOosm+i04l/J7qw4HD8uM3WseJmnGWDPf7gaw3VZ2ibWfCHgUvJqCv/9kwexCN1bG8xYc7ARc9fw8aam+6dCihsKUp8rbRydZAxPPWqm0EclUkiBQ8YsmwI+shmjouGB6ndyH9qeQNGQBXC5kmBAfjIUadImooSLp9auvPI7rJiHR9N7QcYlI0OwgvzltgazJjClGo5j1+jHLkK/PQzuXpRIqm9okWZIJXuekOA65JKSqHwfERoGIBqsSh2zmlSp5bCg649lPXTpb1DyIq6nX4icl9N+lllp9VVfU3eA6C/4306+E99cUEKq/UyxbehuQhHzOzMiPrQeT81xMsOCgdlin6yrtZYuYw4W/LrwrqV6yi4UK8VVZdZ6aQQiBYOZwmJxOz6BkXMswswM="

after_script:
  - echo "after_script"

script:
  - cd ./hexo/time
  - npm install
  - hexo g
  - ls -la
#  - cd .deploy_git
#  - git config user.name "cd_butterfly"
#  - git config user.email "cd_butterfly@qq.com"
#  - git add -A
#  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
#  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:refs/heads/master
  
branches:
  only:
    - hexo