language: node_js
node_js: node

cache:
  directories:
    - node_modules

install: npm install

before_script:
  - npm install -g hexo-cli
  - npm install hexo-deployer-git --save
  - hexo generate

env:
  global:
    - GH-REF: github.com/cd-butterfly/cd-butterfly.github.io.git
    - secure: "b0lvkdh57jckhUDPA0YcWeG6hwMCI8BsgLuS54bsmzpaKO21lcw5f4rKglieHqpryBYBzdsIn87dGQwWBCwEnoabck3KldbWqHNciCfJ8bwzMQ2neAKDQNtv43Dp0vlhIxNTbBVeDbD4n530VqLGrnG4cPQmMgAIUtKyrbs2Y7F5eeAuuTxapcvI1tp9zLzNt7n+fw2chveZLmJaUVnUscz2dv0AKvbd2qUlTtUNdzNBtV1NJXuo7aMo+Z7MLWxwRvXtZL8I4Ml4CBakSFOW+e14WsmcDkwpAOszVCvm1fljpYN6q91yyOAHsAX7ImSdN7jNhCydc/2oRY2InyY/fqoMUGn5hq5up9uZclyxVqOt/4tV9wQE+SioSsSY1LhTfDYqONTXu+N0j7stW7AKqS3B2Pm7PQMWwcvEtPcjUu7DGadCflziW1udRW9bwHiODgV2tYRJMJUGPAhssogmVbsZgjDboFYbe1Diu+RYm1GUkmTxsyVNRcOe7Qxz5tJCWU0IyMalTIMc57k4G5XoQphtw8nlOL/kIjFCnOtMtUheWuoHC6q8JUle9sv4TUW8YAWm1KgDqmKsbRaqMr4ZLrLST5k0WWN+nmIkDIjMwq9Mrtf4om7NqbA23vn2O0hQd73KNGfm+NCGNeWepZI1+kw5YSZ+l9zxD4hV3VH+AYE="

after_script:
  - cd .\hexo\time\.deploy_git
  - git add .
  - git commit -m "Update docs"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:refs/for/master

script:
  echo "success"
