language: node_js
node_js: node

cache:
  directories:
    - node_modules

install: 
    - echo "install"
    - export TZ='Asia/Shanghai'

before_script:
  - echo "before_script"
  - git checkout hexo

env:
  global:
after_script:
  - echo "after_script"

script:
  - cd ./hexo/time
  - npm install
  - hexo g
  - ls -la
  - git clone -b master https://${GH_REF} .deploy_git
  - cp -r ./public/* .deploy_git
  - cd .deploy_git
  - git config user.name ${USER_NAME}
  - git config user.email ${USER_EMAIL}
  - git add -A
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:refs/heads/master
  
branches:
  only:
    - hexo